default:
    @just --list

# Write a version into the files this repository records it in. Called
# by the release tooling, which decides what the version is.
#
# The version is written into each place rather than derived from one.
# The dev shell cannot contain pip2nix - its package set is the one
# pip2nix generates - so importlib.metadata has nothing to read from.
# Every substitution is guarded: sed reports a pattern that matches
# nothing as success, which would release a version half of the files
# never received.
set-version version:
    #!/usr/bin/env bash
    set -euo pipefail
    guard() {
        grep -qE "$2" "$1" || {
            echo "set-version: $1 has no line matching /$2/" >&2
            exit 1
        }
    }
    guard pyproject.toml '^version = "'
    guard pip2nix/__init__.py '^__version__ = "'
    guard docs/conf.py '^release = "'
    guard python-packages.nix '^# Generated by pip2nix '
    grep -A1 'pname = "pip2nix";' python-packages.nix | grep -qE '^ *version = "' || {
        echo "set-version: python-packages.nix has no version below pip2nix's pname" >&2
        exit 1
    }
    sed -i -E 's|^version = ".*"|version = "{{version}}"|' pyproject.toml
    sed -i -E 's|^__version__ = ".*"|__version__ = "{{version}}"|' pip2nix/__init__.py
    sed -i -E 's|^release = ".*"|release = "{{version}}"|' docs/conf.py
    sed -i -E 's|^# Generated by pip2nix .*|# Generated by pip2nix {{version}}|' python-packages.nix
    sed -i -E '/pname = "pip2nix";/{n; s|version = ".*";|version = "{{version}}";|}' python-packages.nix

# Collect the changelog fragments into a section for this version and
# remove them. Called by the release tooling after set-version.
changelog version:
    towncrier build --version {{version}} --yes

# Run the fast test suite, which needs neither nix nor the network
test:
    nix develop --command python3 -m pytest tests/unit/

# Run the tests that need nix or a real package index, selectable by
# the `nix` and `network` markers
test-integration:
    nix develop --command python3 -m pytest tests/integration/

# Run every test there is
test-all: test test-integration

# Run the formatters and the linter over the whole tree. The hooks
# fetch their own environments the first time, so this one needs the
# network once
lint:
    nix develop --command pre-commit run --all-files

# A warning does not fail the run, so the output is worth reading
# Check that every flake output evaluates on every supported system
flake-check:
    nix flake check --all-systems

# Build pip2nix against the default Python
build:
    nix build

# Build every supported Python version and the documentation
build-all:
    nix build .#pip2nix_python311 .#pip2nix_python312 \
        .#pip2nix_python313 .#pip2nix_python314 .#docs

# Build the documentation as HTML
docs:
    nix build .#docs

# Build the documentation as a PDF
docs-pdf:
    nix build .#docs-pdf

# Serve the documentation, rebuilding it as the sources change
docs-watch:
    nix develop .#docs --command sphinx-autobuild docs docs/_build/html

# Build the source distribution and the wheel. Isolation is off so the
# build takes the pinned setuptools instead of fetching one from PyPI
dist:
    nix develop .#release --command pyproject-build --no-isolation

# Install what `dist` built and generate with it. Needs the release
# shell, which carries the `uv` the last pass installs with
dist-check:
    ./scripts/dist-check.sh

# Regenerate python-packages.nix with the pip2nix just built
regenerate: build
    ./result/bin/pip2nix generate --licenses

# Build pip2nix in a virtualenv, the way back from a broken package set
bootstrap:
    python3 -m venv _bootstrap_env
    _bootstrap_env/bin/pip install -e .

# Remove the build artifacts, including bytecode left behind by a module
# that no longer exists
clean:
    rm -rf pip2nix.egg-info dist result result-* _bootstrap_env \
        .pytest_cache docs/_build
    find pip2nix tests -name '__pycache__' -type d -prune -exec rm -rf {} +
    find pip2nix tests -name '*.pyc' -delete
    find pip2nix tests -type d -empty -delete
