# Generated by pip2nix 0.13.0
# See https://github.com/johbo/pip2nix
# A fork of https://github.com/nix-community/pip2nix

{ pkgs, fetchurl, fetchgit, fetchhg }:

self: super: {
  "click" = super.buildPythonPackage rec {
    pname = "click";
    version = "8.4.2";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/fb/e2/79c688af8b210d232694e31e59da9f6ec747bae31c3f5946e4e9b98860d5/click-8.4.2-py3-none-any.whl";
      sha256 = "0xkv35d3qmaj0p6lsbp02vxmgnb13nlpv0b5kmdp85n86rhzdyg6";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.bsd3 ];
    };
  };
  "configobj" = super.buildPythonPackage rec {
    pname = "configobj";
    version = "5.0.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/64/61/079eb60459c44929e684fa7d9e2fdca403f67d64dd9dbac27296be2e0fab/configobj-5.0.6.tar.gz";
      sha256 = "00h9rcmws03xvdlfni11yb60bz3kxfvsj6dg6nrpzj71f03nbxd2";
    };
    format = "setuptools";
    doCheck = false;
    buildInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."six"
    ];
    meta = {
      license = [ pkgs.lib.licenses.bsdOriginal ];
    };
  };
  "jinja2" = super.buildPythonPackage rec {
    pname = "jinja2";
    version = "3.1.6";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/62/a1/3d680cbfd5f4b8f15abc1d571870c5fc3e594bb582bc3b64ea099db13e56/jinja2-3.1.6-py3-none-any.whl";
      sha256 = "0rrgdp707wfs11wk8prswvx6ma418sk16z6xql9hqba93x2y9v45";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [
      self."markupsafe"
    ];
    meta = {
      license = [ pkgs.lib.licenses.bsdOriginal ];
    };
  };
  "markupsafe" = super.buildPythonPackage rec {
    pname = "markupsafe";
    version = "3.0.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/7e/99/7690b6d4034fffd95959cbe0c02de8deb3098cc577c67bb6a24fe5d7caa7/markupsafe-3.0.3.tar.gz";
      sha256 = "160npsg7jh6mbiwy23xm9aqcxgcn0wl33hgx42rmfr2biy09a9kj";
    };
    format = "pyproject";
    doCheck = false;
    buildInputs = [];
    nativeBuildInputs = [
      self."setuptools"
    ];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.bsd3 ];
    };
  };
  "packaging" = super.buildPythonPackage rec {
    pname = "packaging";
    version = "26.3";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/63/34/ba1c580383c9eada3711951fef0795c80b829a078d72188184bcab9dd527/packaging-26.3-py3-none-any.whl";
      sha256 = "076d4fdk71rwap5l9bfh1bx1c3pk1bwjn9p0zm2g94sfiry3y6fp";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.asl20 pkgs.lib.licenses.bsd2 ];
    };
  };
  "pip2nix" = super.buildPythonPackage rec {
    pname = "pip2nix";
    version = "0.13.0";
    src = ./.;
    format = "pyproject";
    doCheck = false;
    buildInputs = [];
    nativeBuildInputs = [
      self."setuptools"
    ];
    propagatedBuildInputs = [
      self."click"
      self."configobj"
      self."jinja2"
      self."packaging"
    ];
    meta = {
      license = [ pkgs.lib.licenses.gpl3Plus ];
    };
  };
  "six" = super.buildPythonPackage rec {
    pname = "six";
    version = "1.17.0";
    src = fetchurl {
      url = "https://files.pythonhosted.org/packages/b7/ce/149a00dd41f10bc29e5921b496af8b574d8413afcd5e30dfa0ed46c2cc5e/six-1.17.0-py2.py3-none-any.whl";
      sha256 = "0x1jdic712dylbnyiqdj4xyxrlx0gaacynmbmkfiym4hxn8z68a7";
    };
    format = "wheel";
    doCheck = false;
    buildInputs = [];
    nativeBuildInputs = [];
    propagatedBuildInputs = [];
    meta = {
      license = [ pkgs.lib.licenses.mit ];
    };
  };
}
