import os
import re
from operator import attrgetter

import pip2nix
from .models.package import indent


def write_output(path, packages, include_lic):
    cache = read_hash_cache(path)

    # Rendering prefetches sources and can fail. Do it before opening the
    # output file, so a failure leaves the previous one intact instead of
    # truncating it to an unparseable fragment.
    rendered_packages = render_packages(packages, include_lic, cache)

    with open(path, "w") as f:
        f.write(_about_comment())
        f.write("{ pkgs, fetchurl, fetchgit, fetchhg }:\n\n")
        f.write("self: super: {\n")
        f.write("  " + indent(2, rendered_packages))
        f.write("\n}\n")


def render_packages(packages, include_lic, cache):
    return "\n".join(
        '"{}" = {}'.format(pkg.name, pkg.to_nix(include_lic=include_lic, cache=cache))
        for pkg in sorted(packages, key=attrgetter("name"))
    )


def read_hash_cache(path):
    """
    Recover the url to hash mapping of a previously generated file, so that
    known sources do not have to be prefetched again.
    """
    if not os.path.exists(path):
        return {}
    with open(path, "r") as f:
        content = re.sub(r"\s+", " ", f.read())
    return dict(re.findall(r'url = "([^"]+)"; sha256 = "([^"]+)"', content))


def _about_comment():
    # TODO: Collapse to one url once the fork merges back upstream
    return (
        "# Generated by pip2nix {}\n".format(pip2nix.__version__)
        + "# See https://github.com/johbo/pip2nix\n"
        + "# A fork of https://github.com/nix-community/pip2nix\n\n"
    )
