import os
import re
from operator import attrgetter

import pip2nix

from .models.package import indent


def write_output(path, packages, nix_licenses):
    # Rendering can fail, and a failure has to leave the previously
    # generated file intact rather than truncate it.
    rendered_packages = render_packages(packages, nix_licenses)

    with open(path, "w") as f:
        f.write(_about_comment())
        f.write("{ pkgs, fetchurl, fetchgit, fetchhg }:\n\n")
        f.write("self: super: {\n")
        f.write("  " + indent(2, rendered_packages))
        f.write("\n}\n")


def render_packages(packages, nix_licenses):
    return "\n".join(
        f'"{pkg.name}" = {pkg.to_nix(nix_licenses)}'
        for pkg in sorted(packages, key=attrgetter("name"))
    )


def read_repository_hashes(path):
    if not os.path.exists(path):
        return {}
    with open(path) as f:
        content = re.sub(r"\s+", " ", f.read())
    repositories = re.findall(
        r'url = "([^"]+)"; rev = "([^"]+)"; sha256 = "([^"]+)"', content
    )
    return {(url, commit_id): sha256 for url, commit_id, sha256 in repositories}


def _about_comment():
    # TODO: Collapse to one url once the fork merges back upstream
    return (
        f"# Generated by pip2nix {pip2nix.__version__}\n"
        + "# See https://github.com/johbo/pip2nix\n"
        + "# A fork of https://github.com/nix-community/pip2nix\n\n"
    )
