from textwrap import dedent
from unittest.mock import Mock

from pip2nix.models.package import WHEEL, PythonPackage
from pip2nix.models.source import Source
from pip2nix.output import read_repository_hashes, write_output

from ..doubles import git_sources, rendering
from .digests import SHA256_HEX


WHEEL_URL = "https://index.example/packages/certifi-2026.1.1-py3-none-any.whl"
GIT_URL = "https://git.example/trytond-account"
COMMIT = "a" * 40


def make_package(name="certifi"):
    return PythonPackage(
        name=name,
        version="2026.1.1",
        dependencies=[],
        source=Source.from_url(WHEEL_URL, sha256=SHA256_HEX),
        format=WHEEL,
    )


def make_git_package():
    return PythonPackage(
        name="trytond-account",
        version="7.0.1",
        dependencies=[],
        source=Source(
            scheme="https", url=GIT_URL, path="/trytond-account", vcs="git", rev=COMMIT
        ),
    )


def test_writes_an_overlay_of_the_packages(tmpdir):
    path = str(tmpdir.join("python-packages.nix"))

    write_output(path, [make_package()], rendering())

    content = tmpdir.join("python-packages.nix").read()
    assert content.startswith("# Generated by pip2nix ")
    assert content.split("\n\n", 1)[1] == dedent("""\
        { pkgs, fetchurl, fetchgit, fetchhg }:

        self: super: {
          "certifi" = super.buildPythonPackage rec {
            pname = "certifi";
            version = "2026.1.1";
            src = fetchurl {
              url = "https://index.example/packages/certifi-2026.1.1-py3-none-any.whl";
              sha256 = "04mmsvw5c0ps2gh6hqwkcs5gyyvmfpr32zvxmv3w68a2mn5kwm39";
            };
            format = "wheel";
            doCheck = false;
            buildInputs = [];
            nativeBuildInputs = [];
            propagatedBuildInputs = [];
          };
        }
        """)


def test_writes_a_header_naming_the_fork_and_upstream(tmpdir):
    path = str(tmpdir.join("python-packages.nix"))

    write_output(path, [make_package()], rendering())

    header = tmpdir.join("python-packages.nix").read().split("\n\n", 1)[0]
    assert header.endswith(
        "# See https://github.com/johbo/pip2nix\n"
        "# A fork of https://github.com/nix-community/pip2nix"
    )


def test_writes_the_packages_sorted_by_name(tmpdir):
    path = str(tmpdir.join("python-packages.nix"))

    write_output(path, [make_package("idna"), make_package("certifi")], rendering())

    content = tmpdir.join("python-packages.nix").read()
    assert content.index('"certifi" =') < content.index('"idna" =')


def test_reads_a_git_source_keyed_on_its_revision(tmpdir):
    path = str(tmpdir.join("python-packages.nix"))
    prefetch_git = Mock(return_value=("the-content-hash", COMMIT, "/store/repo"))

    write_output(
        path, [make_git_package()], rendering(git_sources=git_sources(prefetch_git))
    )

    assert read_repository_hashes(path) == {(GIT_URL, COMMIT): "the-content-hash"}


def test_reads_no_hashes_without_a_previous_file(tmpdir):
    assert read_repository_hashes(str(tmpdir.join("missing.nix"))) == {}
