from textwrap import dedent

import pytest

from pip2nix.errors import ReportError
from pip2nix.models.license import NoLicenses
from pip2nix.models.package import WHEEL, PythonPackage
from pip2nix.models.source import FetchGit, FetchUrl
from pip2nix.output import read_repository_hashes, write_output

from ..doubles import nix_licenses_that_cannot_answer
from .digests import SHA256_BASE32
from .urls import CERTIFI


GIT_URL = "https://git.example/trytond-account"
COMMIT = "a" * 40
CONTENT_HASH = "the-content-hash"


def make_package(name="certifi", licenses=()):
    return PythonPackage(
        name=name,
        version="2026.1.1",
        dependencies=[],
        source=FetchUrl(url=CERTIFI.wheel, sha256=SHA256_BASE32),
        format=WHEEL,
        licenses=list(licenses),
    )


def make_git_package(name="trytond-account", commit_id=COMMIT, sha256=CONTENT_HASH):
    return PythonPackage(
        name=name,
        version="7.0.1",
        dependencies=[],
        source=FetchGit(
            url=f"https://git.example/{name}", rev=commit_id, sha256=sha256
        ),
    )


def test_writes_an_overlay_of_the_packages(tmpdir):
    path = str(tmpdir.join("python-packages.nix"))

    write_output(path, [make_package()], NoLicenses())

    content = tmpdir.join("python-packages.nix").read()
    assert content.startswith("# Generated by pip2nix ")
    assert content.split("\n\n", 1)[1] == dedent("""\
        { pkgs, fetchurl, fetchgit, fetchhg }:

        self: super: {
          "certifi" = super.buildPythonPackage rec {
            pname = "certifi";
            version = "2026.1.1";
            src = fetchurl {
              url = "https://index.example/packages/certifi-2026.1.1-py3-none-any.whl";
              sha256 = "04mmsvw5c0ps2gh6hqwkcs5gyyvmfpr32zvxmv3w68a2mn5kwm39";
            };
            format = "wheel";
            doCheck = false;
            buildInputs = [];
            nativeBuildInputs = [];
            propagatedBuildInputs = [];
          };
        }
        """)


def test_writes_a_header_naming_the_fork_and_upstream(tmpdir):
    path = str(tmpdir.join("python-packages.nix"))

    write_output(path, [make_package()], NoLicenses())

    header = tmpdir.join("python-packages.nix").read().split("\n\n", 1)[0]
    assert header.endswith(
        "# See https://github.com/johbo/pip2nix\n"
        "# A fork of https://github.com/nix-community/pip2nix"
    )


def test_writes_the_packages_sorted_by_name(tmpdir):
    path = str(tmpdir.join("python-packages.nix"))

    write_output(path, [make_package("idna"), make_package("certifi")], NoLicenses())

    content = tmpdir.join("python-packages.nix").read()
    assert content.index('"certifi" =') < content.index('"idna" =')


def test_leaves_the_previously_generated_file_intact_when_rendering_fails(tmpdir):
    path = str(tmpdir.join("python-packages.nix"))
    write_output(path, [make_package()], NoLicenses())
    previously_generated = tmpdir.join("python-packages.nix").read()

    with pytest.raises(ReportError):
        write_output(
            path,
            [make_package(licenses=["MIT"])],
            nix_licenses_that_cannot_answer(),
        )

    assert tmpdir.join("python-packages.nix").read() == previously_generated


def test_reads_a_git_source_keyed_on_its_commit_id(tmpdir):
    path = str(tmpdir.join("python-packages.nix"))

    write_output(path, [make_git_package()], NoLicenses())

    assert read_repository_hashes(path) == {(GIT_URL, COMMIT): CONTENT_HASH}


def test_pairs_each_commit_id_with_the_url_of_its_own_block(tmpdir):
    path = str(tmpdir.join("python-packages.nix"))
    other = "b" * 40

    write_output(
        path,
        # `certifi` sorts first and carries a `fetchurl` block, whose url
        # a pattern reaching past its own block would pair with the
        # commit id below it.
        [
            make_package(),
            make_git_package(sha256=f"hash-of-{COMMIT}"),
            make_git_package("trytond-party", other, f"hash-of-{other}"),
        ],
        NoLicenses(),
    )

    assert read_repository_hashes(path) == {
        (GIT_URL, COMMIT): f"hash-of-{COMMIT}",
        ("https://git.example/trytond-party", other): f"hash-of-{other}",
    }


def test_reads_no_hashes_without_a_previous_file(tmpdir):
    assert read_repository_hashes(str(tmpdir.join("missing.nix"))) == {}
